#!/bin/sh

# -------------------------------------------------------------------------
# This installs packages, apps, etc that are essential. 
# Adapt to your taste.
# -------------------------------------------------------------------------
fancy_echo "Moving on to the apps, gems, and pips..."

fancy_echo "Cleaning up old Homebrew content ..."
brew cleanup 2> /dev/null

# -------------------------------------------------------------------------
# Gatekeeper, turn it off
# -------------------------------------------------------------------------

sudo spctl --master-disable

# -------------------------------------------------------------------------
# Apps
# -------------------------------------------------------------------------
fancy_echo "Install Homebrew formulae"
brew bundle -v --file=stuffs/Brewfile
fancy_echo "Formulae installed"

fancy_echo "Install Mac App Store apps"
brew install mas
brew bundle -v --file=stuffs/mas.txt
fancy_echo "Mac App Store apps installed"

# -------------------------------------------------------------------------
# Gems
# -------------------------------------------------------------------------
fancy_echo "Installing gems"
gem update --system
bundle install --system --gemfile=stuffs/Gemfile
rbenv rehash

append_to_zshrc 'LUNCHY_DIR=$(dirname `gem which lunchy`)/../extras
  if [ -f $LUNCHY_DIR/lunchy-completion.zsh ]; then
    . $LUNCHY_DIR/lunchy-completion.zsh
  fi'

# accept xcode license now -- comment if not installing it
sudo xcodebuild -license accept

# -------------------------------------------------------------------------
# Fonts
# -------------------------------------------------------------------------
fancy_echo "Get the old fonts, install to ~/library/fonts"

cp -a /stuffs/fonts/. ~/Library/Fonts/

# -------------------------------------------------------------------------
# NPM
# -------------------------------------------------------------------------
fancy_echo "Updating NPM and install packages"
npm i -g npm
npm -g install fkill vtop spoof  eslint babel-eslint eslint-config-standard eslint-config-prettier eslint-plugin-prettier  browser-sync fast-cli grunt gulp gulp-scss-lint javascripting jshint n parcel-bundler tachyons-cli postcss-cli speed-test splash-cli stacks-cli switch-php npm yo now tldr prettier

fancy_echo "Installing Python packages"
sudo easy_install pip
pip install -r stuffs/thepips.txt

# -------------------------------------------------------------------------
# Set up local PHP dev environment
# -------------------------------------------------------------------------
fancy_echo "Set up Valet Plus"
mkdir ~/code
composer self-update
composer global require weprovide/valet-plus
valet fix 
valet install
wp package install git@github.com:aaemnnosttv/wp-cli-valet-command.git
cd ~/code
valet park
valet domain taco
brew services restart --all

if [ -f ".grabs.local" ]; then
  fancy_echo "Download apps from S3 *now*, these are time limited by default"
  # shellcheck disable=SC1090
  . "./grabs.local"
fi

fancy_echo "All apps installed!"
